import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import fs from "fs";
import Link from "next/link";
import matter from "gray-matter";

export async function getStaticProps() {
  const folder = "posts";
  const fileNames = fs.readdirSync(folder);
  const markdownFiles = fileNames.filter((file) => file.endsWith(".md"));
  const posts = markdownFiles.map((fileName) => {
    const content = fs.readFileSync(`${folder}/${fileName}`, "utf-8");
    const matterResult = matter(content);
    return {
      title: matterResult.data.title,
      date: matterResult.data.date,
      subtitle: matterResult.data.subtitle,
      slug: fileName.replace(".md", ""),
    };
  });

  return {
    props: {
      blogs: posts,
    },
  };
}

export const Blogs = ({ blogs }) => {
  return (
    <div className="blogs">
      <h1>All blogs</h1>
      {blogs.map((blog, i) => (
        <div
          key={i}
          // className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <Link href={`/posts/${blog.slug}`}>
            <h2>{blog.title}</h2>
            <p>{blog.subtitle}</p>
            <p>{blog.date}</p>
          </Link>
        </div>
      ))}
    </div>
  );
};

export default function Home({ blogs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blogs blogs={blogs} />
    </div>
  );
}
